### ISSUE TITLE
🐞 - Project does not start with Angular 15

### ISSUE THREAD

**Issue by Foprta** [Tinkoff/maskito#130]
### Which package(s) are the source of the bug?

@maskito/core

### Description

Cannot start project with **Angular 15**.

```
./node_modules/@maskito/core/src/index.js:1:0 - Error: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> export { MASKITO_DEFAULT_OPTIONS } from './lib/constants';
| export { Maskito } from './lib/mask';
| export { maskitoPipe } from './lib/utils';
```

Used **@angular-devkit/build-angular** version: **15.1.4**

### Maskito version

0.1.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@Foprta Thanks!

I can reproduce this issue with Angular 13 too.
Locally this solution https://github.com/Tinkoff/maskito/pull/131 helps to fix issue.

I will publish `0.1.1` now and check it again.

**Comment by nsbarsukov** [comment]
@Foprta `0.1.1`-version was released.

I've checked Angular 13 and Angular 15 – it works now.

**Comment by Foprta** [comment]
It works now, much appreciated!
