### ISSUE TITLE
🐞 - Input is not formatting when setting `FormControl` value programmatically

### ISSUE THREAD

**Issue by Foprta** [Tinkoff/maskito#172]
### Which package(s) are the source of the bug?

@maskito/angular

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-jlgxte

### Description

Input is not formatted after setting value via FormControl methods `setValue`, `patchValue`, `reset`.

### Maskito version

0.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Foprta** [comment]
Since there is no function to get a resulted formatting like `formatValue(value: string): string` i've decided to use a hack to fire `input` event and trigger all the `maskito` processing:
```
    const originalWriteValue = this.ngControl.valueAccessor.writeValue.bind(this.ngControl.valueAccessor);

    this.ngControl.valueAccessor.writeValue = (obj: any) => {
      originalWriteValue(obj);

      this.elRef.nativeElement.dispatchEvent(new Event("input"));
    };
```

**Comment by waterplea** [comment]
We probably also need a way to format an arbitrary string with given `MaskitoOptions` 🤔

**Comment by Foprta** [comment]
Would be great to have this method in the `Maskito` class itself.

**Comment by nsbarsukov** [comment]
> Input is not formatted after setting value via FormControl methods setValue, patchValue, reset.

Maskito libraries were created to prevent **user** from typing invalid value.
Maskito listens `beforeinput` and `input` events. 
Programatic changes of input's value (by developer) don't trigger these events!
Of course, we can use `MutationObserver` to detect these programatic changes. But it is overkill.

**Maskito is based on the assumption that developer is capable to programatically patch input with valid value.**

However, Alex suggests good idea that we can add utility-helper for these cases:

> We probably also need a way to format an arbitrary string with given `MaskitoOptions` 🤔

This issue will be solved in the following issue
* https://github.com/Tinkoff/maskito/issues/175

**Comment by waterplea** [comment]
> Well, it is not affects me as i'm not using the `@maskito/angular` library, but as an Angular developer i assume that `angular`-library would properly support _Angular features_ by default. Otherwise it seems like a useless library, because you still need to implement your own _Angular logic_.

@nsbarsukov I think other masking solutions watch for programmatic changes too.

**Comment by nsbarsukov** [comment]
> @nsbarsukov I think other masking solutions watch for programmatic changes too.

We can take our legacy [text-mask](https://text-mask.github.io/text-mask/) as an example.

Programatic update of the value via vanilla JS doesn't trigger value's validations.
<img width="1270" alt="Screenshot 2023-03-06 at 14 52 42" src="https://user-images.githubusercontent.com/35179038/223103549-66c18bd1-a40f-4006-bbb8-92af93aa29b8.png">


Angular package  `angular2-text-mask` [implements `ControlValueAccessor`](https://github.com/text-mask/text-mask/blob/master/angular2/src/angular2TextMask.ts#L41).
Our library doesn't do it (because it doesn't always have direct access to native input).
We suppose that library can be used with Taiga UI, Material, Ant and other design libraries.
