### ISSUE TITLE
🚀 - New utility `maskitoUnmaskNumber`

### ISSUE THREAD

**Issue by Foprta** [Tinkoff/maskito#174]
### Which package(s) are the source of the bug?

@maskito/angular

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-7qqzas

### Description

Press "Log value"

**Expected Result:**
`1234` in console

**Actual Result:**
`1 234` in console

### Maskito version

0.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Foprta** [comment]
Actually i'm using my own directive with `@maskito` and found a workaround:

```
constructor(private elRef: ElementRef, private ngControl: NgControl) {
    const original = this.ngControl.valueAccessor!.registerOnChange;

    this.ngControl.valueAccessor!.registerOnChange = (fn: (_: unknown) => void) => {
      return original.call(this.ngControl.valueAccessor, (value: unknown) => {
        if (typeof value !== "string") {
          return fn(value);
        }

        const parsedValue = parseFloat(value.replaceAll(this.thousandSeparator, ""));

        if (Number.isNaN(parsedValue)) {
          return fn(null);
        }

        return fn(parsedValue);
      });
    };
  }
```

**Comment by waterplea** [comment]
But once you start typing any value in the input, it would become a string anyway. It's the responsibility of the component to interpret this string as number and store it as number in control. That said, we should definitely help with that, maybe provide a `maskitoUnmaskNumber(formatted: string): number` utility or something like that.

**Comment by nsbarsukov** [comment]
Within this issue we need to create this simple utility:

```ts
export function maskitoUnmaskNumber(maskedValue: string, decimalSeparator: string): number {
    return Number(
        maskedValue
            .replace(new RegExp(`[^\\d\\${decimalSeparator}]`, 'g'), '')
            .replace(decimalSeparator, '.')
    );
}

maskitoUnmaskNumber('1 000 000,37', ',') // 1000000.37
```

**Comment by waterplea** [comment]
> Within this issue we need to create this simple utility:
> 
> ```ts
> export function maskitoUnmaskNumber(maskedValue: string, decimalSeparator: string): number {
>     return Number(
>         maskedValue
>             .replace(new RegExp(`[^\\d\\${decimalSeparator}]`, 'g'), '')
>             .replace(decimalSeparator, '.')
>     );
> }
> 
> maskitoUnmaskNumber('1 000 000,37', ',') // 1000000.37
> ```

What about a custom thousand separator?

**Comment by nsbarsukov** [comment]
> What about a custom thousand separator?

RegExp above will deal with any custom thousand separator :)
