### ISSUE TITLE
🚀 - Can you add the feature to use a placeholder like in the documentation?

### ISSUE THREAD

**Issue by whyRonning** [Tinkoff/maskito#179]
### Which package(s) are relevant/related to the feature request?

@maskito/core, @maskito/angular

### Description

![image](https://user-images.githubusercontent.com/45920525/223981400-bc6153ed-6ce1-4145-a620-bb2c77dd220e.png)

**Comment by whyRonning** [comment]
@nsbarsukov I understand, but it's easier to use this package without downloading other packages.For example,I plan to use only this package, but I can't use this library, because it too large

**Comment by nsbarsukov** [comment]
@whyRonning the discussed feature will be developed in this issue:
- https://github.com/Tinkoff/maskito/issues/181
