### ISSUE TITLE
🚀 - Add `maskitoWithGuide` processors

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#181]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

See this discussion: https://github.com/Tinkoff/maskito/issues/179

We need to add possibility to add guide.

### Proposed solution
```ts
import { Maskito, maskitoPipe, maskitoWithGuide } from '@maskito/core';
import { maskitoWithGuide } from '@maskito/kit';


const { guidePreprocessor, guidePostprocessor } = maskitoWithGuide('dd/mm/yyyy')
 
const maskedInput = new Maskito(element, {
  // ...
  preprocessor: maskitoPipe(
    guidePreprocessor,
    // ...,
    
  ),
  postprocessor: maskitoPipe(
    // ...,
    guidePostprocessor,
  ),
  overwriteMode: 'replace', // ONLY THIS
});
```

**Additional tasks:**
- [ ] Add page `With Guide` to `Recipes` section.
- [ ] Add `Phone` with guide example to this new page
- [ ] Add `Date` with guide example to this new page

**Comment by waterplea** [comment]
Let's just return `MaskitoOptions` from this utility so that `overwriteMode` is also present and people can write:

```ts
const mask = {
  ...maskitoWithGuide(...)
  mask: ...
}
```

**Comment by nsbarsukov** [comment]
> Let's just return `MaskitoOptions` from this utility so that `overwriteMode` is also present and people can write:
> 
> ```ts
> const mask = {
>   ...maskitoWithGuide(...)
>   mask: ...
> }
> ```

The problem of this approach that it is diffucult to extend it with other processors 🤔

**Comment by waterplea** [comment]
But if you need it you can destruct it earlier.
