### ISSUE TITLE
🚀 - New utility `maskitoPreventedInputListener`

### ISSUE THREAD

**Issue by demensky** [Tinkoff/maskito#233]
### Which package(s) are relevant/related to the feature request?

@maskito/core, @maskito/angular

### Description

An event that is emitted when the user's input has been canceled would be useful.

This will explicitly signal to the user that the data they enter has been rejected. For example: Implement flashing of the input field with a red border (with subsequent fading). This will create a UX similar to validators.

**Comment by nsbarsukov** [comment]
I hope, this task can be solved without extending of the Public API.
We can listen `beforeinput` events and use [defaultPrevented](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented) property.

See this example:
https://stackblitz.com/edit/canceled-input-listener?devToolsHeight=80&file=index.ts

@demensky what do you think about it ? Does it cover all required cases ?
If yes, probably we can transform this task into `Add new recipe "<topic name>"`

**Comment by nsbarsukov** [comment]
> But it would also be prevented if the mask changes results? For example if it adds a static char like space.

See my Stackblitz. I've taken it into consideration.

**Comment by nsbarsukov** [comment]
Let's discuss if this solution is acceptable or it is a little bit hacky.

**Comment by nsbarsukov** [comment]
@demensky 
I am not sure that the following behaviour is correct one
```
12| => Type `#` => 12:|
```

It is ambiguity for user that pressing ANY key causes insertion of fixed character.
Probably, I need to create bug for this case 🤔

**Comment by nsbarsukov** [comment]
Speaking about your original request.

> This will explicitly signal to the user that the data they enter has been rejected. For example: Implement flashing of the input field with a red border (with subsequent fading). This will create a UX similar to validators.

I think we can create a utility based on [this solution](https://stackblitz.com/edit/canceled-input-listener?devToolsHeight=80&file=index.ts).

**Vanilla JavaScript:**
```ts
import {maskitoPreventedInputListener} from '@maskito/kit'

const signal = () => console.info('INVALID!');

const destroyFn = maskitoPreventedInputListener(element, signal);

// ... (after element is detached from DOM)
destroyFn();
```

**Angular way (directive):**
```ts
class MaskitoPreventedInputDirective {
    @Output()
    preventedInput = new Observable(
        // ... maskitoPreventedInputListener inside
    )

    ngOnDestroy() {
        // ...
    }
}
```

```html
<input [maskito]="..." (preventedInput)="signal($event)"> 
```

**Comment by waterplea** [comment]
We can probably enclose it in a callback:

```ts
input.addEventListener(
  'beforeinput',
  () => {
    const initialValue = input.value;

    input.addEventListener('beforeinput', (event) => {
      if (event.defaultPrevented && initialValue === input.value) {
        console.log('INVALID');
      }
    }, { once: true });
  },
  { capture: true }
);
```

**Comment by nsbarsukov** [comment]
@demensky 

I've understood your case with prevented input, it is okey.
> This will explicitly signal to the user that the data they enter has been rejected. For example: Implement flashing of the input field with a red border (with subsequent fading). This will create a UX similar to validators.

But could you also explain me the following case, please :
> There is indeed an ambiguity in the current behavior. It might make sense to do something like this:
> 
> Type `#`. Emit: REPLACE event.

When do you need to be notified about `REPLACE event` ?

**Comment by nsbarsukov** [comment]
> But I think it's not worth adding cosmetic changes here, for example:

But for this cases you should not edit [Mask Expression](https://tinkoff.github.io/maskito/core-concepts/mask-expression).
You should not "detect" these cosmetic changes for it.

There are 2 ways to define mask expression: pattern mask and RegExp mask.

**Comment by nsbarsukov** [comment]
I will investigate this idea.
But at the first glance, it seems impossible to distinguish "cosmetic" changes from "significant" changes.

Sorry :(

___

I mean for every particular case/mask you can create the such "detector" in your project (you should improve the stackblitz example above).
But creation of something like "general solution" can be overcomplicated.

**Comment by nsbarsukov** [comment]
Within this issue let's create [this utility](https://github.com/Tinkoff/maskito/issues/233#issuecomment-1488085279).
