### ISSUE TITLE
🚀 - Padding 0 for decimals to precision

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/maskito#250]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

We need two modes, padding zeroes to specific precision and leaving decimals untouched. In Taiga UI leaving decimals untouched is currently done with `Infinity` passed as precision, but we might also need to be able to set particular precision without zero padding.

**Comment by nsbarsukov** [comment]
- https://github.com/Tinkoff/taiga-ui/pull/4114
