### ISSUE TITLE
🐞 - ⌘⇧Z stops working if the layout is not English

### ISSUE THREAD

**Issue by demensky** [Tinkoff/maskito#310]
### Which package(s) are the source of the bug?

@maskito/core

### Playground Link

https://tinkoff.github.io/maskito/recipes/phone#us

### Description

https://github.com/Tinkoff/maskito/assets/10235949/88d2f238-f5e0-4b62-9b47-16b360578aa0

### Maskito version

0.12.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
**TIL**

Use english keyboard + press `Cmd` + `Shift` + `Z` => `keyboardEvent.key` equal to `z`.
Use NOT english keyboard + press `Cmd` + `Shift` + `Z` => `keyboardEvent.key` equal to `Z` (uppercase).

😄

**Comment by nsbarsukov** [comment]
@demensky Do you want to become contributor of this project ?

The only required change is this line:
https://github.com/Tinkoff/maskito/blob/b6e822859ba233689dbeccd24d290f29ca190b97/projects/core/src/lib/mask.ts#L38

Something like:

```
key.toLowerCase()
```

or  use [KeyboardEvent: code property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code).

**Comment by nsbarsukov** [comment]
I think that [KeyboardEvent: code property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) is the best solution 🤔

**Comment by waterplea** [comment]
> I think that [KeyboardEvent: code property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) is the best solution 🤔

Just gotta make sure we test it with different keyboard layouts.

**Comment by demensky** [comment]
Okay, @nsbarsukov, I'll do a PR today tonight.

**Comment by nsbarsukov** [comment]
This issue is not solved completely.

Further improvements will be done in this issue:
* https://github.com/Tinkoff/maskito/issues/315
