### ISSUE TITLE
🚀 - Find better layout-independent way to detect `Undo` and `Redo` shortcuts

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#315]
### Which package(s) are relevant/related to the feature request?

@maskito/core

### Problem description
**Maskito** uses [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) property to detect undo/redo shortcuts.

https://github.com/Tinkoff/maskito/blob/5783e766a657abcf0fc7f8a8d12ac1bf412dc18a/projects/core/src/lib/utils/dom/history-events.ts#L1-L14

It works for some keyboard layouts (for example, English).
But not all languages have the same position of these keys.

For example, in German keyboard keys  `Z` and `Y` are swapped.
<img width="714" alt="Screenshot 2023-05-23 at 12 07 49" src="https://github.com/Tinkoff/maskito/assets/35179038/0eb84310-6dd4-4974-9287-c7f836aba5ce">
And the current solution does not properly work for German keyboard.

### Proposed solutions
We need investigate this issue and look for better alternatives.
For example, we can use legacy [KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) property.

**Comment by demensky** [comment]
## Undo hotkey

| Layout  | Browser | OS      | `code`  | `key` | `keyCode` | `which` |
| ------- | ------- | ------- | :-----: | :---: | :-------: | :-----: |
| English | Chrome  | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Chrome  | Windows | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Chrome  | Linux   |    ?    |   ?   |     ?     |    ?    |
| English | Chrome  | Android | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Safari  | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Firefox | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Firefox | Windows | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Firefox | Linux   |    ?    |   ?   |     ?     |    ?    |
| English | Firefox | Android |    ?    |   ?   |     ?     |    ?    |
| Russian | Chrome  | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| Russian | Chrome  | Windows | `KeyZ`  |  `я`  |   `90`    |  `90`   |
| Russian | Chrome  | Linux   |    ?    |   ?   |     ?     |    ?    |
| Russian | Chrome  | Android |    ?    |   ?   |     ?     |    ?    |
| Russian | Safari  | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| Russian | Firefox | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| Russian | Firefox | Windows | `KeyZ`  |  `я`  |   `90`    |  `90`   |
| Russian | Firefox | Linux   |    ?    |   ?   |     ?     |    ?    |
| Russian | Firefox | Android |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Chrome  | macOS   | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Chrome  | Windows | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Chrome  | Linux   |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Chrome  | Android |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Safari  | macOS   | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Firefox | macOS   | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Firefox | Windows | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Firefox | Linux   |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Firefox | Android |    ?    |   ?   |     ?     |    ?    |

## Redo hotkey

| Layout  | Browser | OS      | `code`  | `key` | `keyCode` | `which` |
| ------- | ------- | ------- | :-----: | :---: | :-------: | :-----: |
| English | Chrome  | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Chrome  | Windows | `KeyZ`  |  `Z`  |   `90`    |  `90`   |
| English | Chrome  | Linux   |    ?    |   ?   |     ?     |    ?    |
| English | Chrome  | Android | `KeyZ`  |  `Z`  |   `90`    |  `90`   |
| English | Safari  | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Firefox | macOS   | `KeyZ`  |  `z`  |   `90`    |  `90`   |
| English | Firefox | Windows | `KeyZ`  |  `Z`  |   `90`    |  `90`   |
| English | Firefox | Linux   |    ?    |   ?   |     ?     |    ?    |
| English | Firefox | Android |    ?    |   ?   |     ?     |    ?    |
| Russian | Chrome  | macOS   | `KeyZ`  |  `Z`  |   `90`    |  `90`   |
| Russian | Chrome  | Windows | `KeyZ`  |  `Я`  |   `90`    |  `90`   |
| Russian | Chrome  | Linux   |    ?    |   ?   |     ?     |    ?    |
| Russian | Chrome  | Android |    ?    |   ?   |     ?     |    ?    |
| Russian | Safari  | macOS   | `KeyZ`  |  `Z`  |   `90`    |  `90`   |
| Russian | Firefox | macOS   | `KeyZ`  |  `Z`  |   `90`    |  `90`   |
| Russian | Firefox | Windows | `KeyZ`  |  `Я`  |   `90`    |  `90`   |
| Russian | Firefox | Linux   |    ?    |   ?   |     ?     |    ?    |
| Russian | Firefox | Android |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Chrome  | macOS   |   NO    |  NO   |    NO     |   NO    |
| Dvorak  | Chrome  | Windows | `Slash` |  `Z`  |   `90`    |  `90`   |
| Dvorak  | Chrome  | Android |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Chrome  | Linux   |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Safari  | macOS   | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Firefox | macOS   | `Slash` |  `z`  |   `90`    |  `90`   |
| Dvorak  | Firefox | Windows | `Slash` |  `Z`  |   `90`    |  `90`   |
| Dvorak  | Firefox | Linux   |    ?    |   ?   |     ?     |    ?    |
| Dvorak  | Firefox | Android |    ?    |   ?   |     ?     |    ?    |
