### ISSUE TITLE
🚀 - Processors should accept array of functions + `maskitoPipe` deletion

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#322]
### Which package(s) are relevant/related to the feature request?

@maskito/core, @maskito/kit

### Step 1
Replace these lines
https://github.com/Tinkoff/maskito/blob/4c5a7f64b9a8ac209584c75e17ec022674b87c1b/projects/core/src/lib/types/mask-options.ts#L8-L9
with
```ts
 readonly preprocessors?: MaskitoPreprocessor[]; 
 readonly postprocessors?: MaskitoPostprocessor[]; 
```
(plural form + new type)

___

### Step 2

Deprecate this utility
https://github.com/Tinkoff/maskito/blob/4c5a7f64b9a8ac209584c75e17ec022674b87c1b/projects/core/src/lib/utils/pipe.ts#L12-L19
___

### Step 3

All mask generators from `@maskito/kit` should return `Required<MaskitoOptions>`.

___

### Step 4

Update documentation
https://tinkoff.github.io/maskito/core-concepts/processors

**Comment by waterplea** [comment]
Those arrays have to be `readonly`
