### ISSUE TITLE
🚀 - add fraction separator

### ISSUE THREAD

**Issue by Eugeno** [Tinkoff/maskito#361]
### Description

To transform this:
![image](https://github.com/Tinkoff/maskito/assets/23382920/9cdc2ffc-3128-488d-b679-a7b3b38e6c39)

Into `12 345,678 90`

**Comment by waterplea** [comment]
I have never seen decimals formatted like that. Admittedly, I very rarely use more than 2 orders, but I just tested a few crypto interfaces and they do not do that either. Can you elaborate why you need that feature?

**Comment by Eugeno** [comment]
To be honest, there's no such real task on the project, the request is purely for typography :)

> In some countries, these "digit group separators" are only employed to the left of the decimal separator; in others, they are also used to separate numbers with a long fractional part. [Wiki](https://en.wikipedia.org/wiki/Decimal_separator).

> ![image](https://github.com/Tinkoff/maskito/assets/23382920/ec40bf65-f388-4ace-8116-8dda3fdb7c3c)
[Milchin](https://www.artlebedev.ru/izdal/spravochnik-izdatelya-i-avtora-2021/)
