### ISSUE TITLE
🐞 - decimalZeroPadding & Postfix incompatible

### ISSUE THREAD

**Issue by selcuk-sahin** [Tinkoff/maskito#368]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/pjvley?file=mask.ts

### Description

When I use   
`decimalZeroPadding: true ` with a postfix, such as `postfix: ' TL'` I'm getting this weird behavior, where postfix is duplicated.

### Maskito version

    "@maskito/core": "1.2.0",     "@maskito/kit": "1.2.0"

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Duplicates #367
