### ISSUE TITLE
🐞 - `Number` trim zeroes after deleting of leading digit will break UX

### ISSUE THREAD

**Issue by seriouzly** [Tinkoff/maskito#370]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://tinkoff.github.io/maskito/kit/number/API?thousandSeparator=_&precision=2

### Description

1. Open https://tinkoff.github.io/maskito/kit/number/API?thousandSeparator=_&precision=2
2. Type 1000000 (one million)
3. Want to change to 2000000 (two million), move caret after the first digit (1|_000_000)
4. Press Backspace and after press `2`.

**Expected behaviour:** `2_000_000`
Actual behaviour: `20`

1. Open https://tinkoff.github.io/maskito/kit/number/API?thousandSeparator=_&precision=2
2. Type 10023.
3. Want to change to 20023, move caret after the first digit (1|0_023).
4. Press Backspace and after press `2`.

**Expected behaviour:** `20_023`
Actual behaviour: `223`

Current behaviour is break usual UX because differs from the standard input actions.
Related issue: https://github.com/Tinkoff/maskito/issues/266.
**Workaround:** add a flag to select behavior.

### Maskito version

1.2.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by waterplea** [comment]
That happens quite often with number masks and it always annoys me :) I wonder how we can handle it, perhaps not trim zeroes if caret is before them?

**Comment by nsbarsukov** [comment]
@waterplea Should we convert this postprocessor to plugin (and trigger it only on blur) ?

https://github.com/Tinkoff/maskito/blob/225049693d0297caa22e429e96f7dc67f700e7d4/projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts#L5-L15

**Comment by waterplea** [comment]
@nsbarsukov seems reasonable 👍
