### ISSUE TITLE
🚀 - `DateRange` add configurable parameter `rangeSeparator`

### ISSUE THREAD

**Issue by WoodenPC** [Tinkoff/maskito#375]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

Привет, можно ли добавить возможность указать разделитель между датами? Сейчас это тире с 2мя пробелами, хочется прокинуть свою строку
![image](https://github.com/Tinkoff/maskito/assets/25397745/a0d6aca8-33af-45b9-8b6c-5b7de2469d43)

**Comment by nsbarsukov** [comment]
https://github.com/Tinkoff/maskito/blob/8554fead2a2474104f0674fb597cf86467274943/projects/kit/src/lib/masks/date-range/date-range-mask.ts#L13

**Comment by WoodenPC** [comment]
@nsbarsukov fyi PR created. I tried my best. P.S. i am react developer, so dont be mad if you see some bad angular code :)
