### ISSUE TITLE
🚀 - `MaskitoDateMode` supports `yyyy` & `mm/yyyy` & `yyyy/mm` 

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#381]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

The following ready-to-use masks supports new date-modes `yyyy`, `mm/yyyy` and `yyyy/mm` :

* [Date](https://tinkoff.github.io/maskito/kit/date)
* [DateRange](https://tinkoff.github.io/maskito/kit/date-range)

**Comment by Reaverart** [comment]
Looks like exactly what we wish to see, ty!

**Comment by nsbarsukov** [comment]
**UPDATE:** [DateTime](https://tinkoff.github.io/maskito/kit/date-time) does not require support of this new modes.
