### ISSUE TITLE
🚀 - `MaskitoTimeMode` supports `HH`

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#382]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

Add `HH` to

https://github.com/Tinkoff/maskito/blob/8210896d2095a44e79a27a38e4c8745e2beccdb7/projects/kit/src/lib/types/time-mode.ts#L1

Don't forget to update [Time](https://tinkoff.github.io/maskito/kit/time) and [DateTime](https://tinkoff.github.io/maskito/kit/date-time)

**Comment by Reaverart** [comment]
Looks like exactly what we wish to see, ty!
