### ISSUE TITLE
🐞 - `Number` should drop items from `decimalPseudoSeparators` if any is equal to `thousandSeparator`

### ISSUE THREAD

**Issue by namereva** [Tinkoff/maskito#388]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

`https://tinkoff.github.io/maskito/kit/number/API?sandboxExpanded=true&precision=2&decimalPseudoSeparators$=0&decimalSeparator=.&decimalZeroPadding=false&thousandSeparator=%C2%A0,`

### Description

The bug appear when we use decimalPseudoSeparators with thousandSeparator comma.
```ts
const OPTIONS = {
  precision: 2,
  decimalPseudoSeparators: ['.', ',', 'б', 'ю'],
  thousandSeparator: ',',
  decimalSeparator: '.',
};
```

### Maskito version

1.4.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@namereva Hello!

I think that `decimalPseudoSeparators` must not include `thousandSeparator` 🤔

**Comment by namereva** [comment]
Sorry, miss click( 
I thought it was like alias for buttons

**Comment by namereva** [comment]
Anyway this is looks like bug. May be docs should be improved. For example added alert about this case.

**Comment by nsbarsukov** [comment]
We can internally drop items from `decimalPseudoSeparators` if anything is equal of `thousandSeparator` 👌
